### ISSUE TITLE
Bug (possibly misunderstanding) with categoricals_append() and categoricals_pop()

### ISSUE THREAD

**Issue by Lucasc-99** [bits-back/bits-back#10]
`I` have been using your rans implementation, specifically the higher level functions for categorial distributions you have provided in utils.py.

I'm encountering a bug where the wrong symbols are popped from the stack. This bug only occurs for certain (precision, category count) pairings. It does not depend on the actual values that are put in, but it does depend on the selected probabilities and seems to happen more often with uniforms.

Here's an example from one of my testing runs (with uniform): 

![ransissue](https://github.com/bits-back/bits-back/assets/65745589/8adccb01-0f95-48dd-a851-e68b910e0db8)

Each point represents a failure. The exact points change depending on how many values I push before I start popping from the stack, but the pattern shown above stays about the same.

I suspect it has something to do with this code here in utils.py:

```python
def create_categorical_buckets(probs, precision):
    buckets = np.rint(probs * ((1 << precision) - len(probs))) + np.ones(probs.shape)
    bucket_sum = sum(buckets)
    if not bucket_sum == 1 << precision:
        i = np.argmax(buckets)
        buckets[i] += (1 << precision) - bucket_sum
    assert sum(buckets) == 1 << precision
    return np.insert(np.cumsum(buckets), 0, 0)  # this could be slightly wrong
```
You specifically mention the last line could be slightly wrong. Do you think this is the cause of the issue? If so, how do I go about making this implementation not slightly wrong.

Any help would be greatly appreciated!

**Comment by j-towns** [comment]
Hi @Lucasc-99, thanks very much for raising this. This could be caused by a numerical rounding issue. Please can you provide a specific set of example inputs (message, probs, precision, data) which cause incorrect decoding? That will help to identify the cause.

**Comment by j-towns** [comment]
Also, in case you haven't seen them, I have written a couple of slightly more mature tools which should be more reliable. [Craystack](https://github.com/j-towns/craystack) and a high performance version in JAX, [Crayjax](https://github.com/j-towns/crayjax).

**Comment by Lucasc-99** [comment]
Hey James,

I switched to using craystack and am no longer having this issue. Thank you, and great work with this library!
